language: cpp

matrix:
  include:
    - env: NAME="Ubuntu 64 bits"
      sudo: required
      services:
        - docker
      before_install:
        - docker run -d --name ubuntu-20-04 -v $(pwd):/travis ubuntu:20.04 tail -f /dev/null
      install:
        - docker exec -e DEBIAN_FRONTEND=noninteractive -t ubuntu-20-04 bash -c "apt-get -qq update; apt-get install -y git; apt-get install -y cmake; apt-get install -y build-essential;  apt-get install -y wget;  apt-get install -y tar;  apt-get install -y  libgfortran5; apt-get install -y libgmsh-dev; apt-get install -y libeigen3-dev"
      script:
         - docker exec -t ubuntu-20-04 bash -c "cd /travis; ./build_travis.sh;"
