language: cpp

os: linux

dist: focal

compiler: 
  - gcc
  - clang

install:
  - sudo apt-get update
  - sudo apt-get install -y cmake
  - sudo apt-get install -y wget
  - sudo apt-get install -y tar
  - sudo apt-get install -y libgfortran5 
  - sudo apt-get install -y libgmsh-dev 
  - sudo apt-get install -y libeigen3-dev
  - wget http://gmsh.info/bin/Linux/gmsh-4.6.0-Linux64-sdk.tgz 
  - tar -xf gmsh-4.6.0-Linux64-sdk.tgz 
  - wget https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.gz 
  - tar -xf eigen-3.3.7.tar.gz

before_script:
  - export PATH=${PWD}/gmsh-4.6.0-Linux64-sdk/bin:${PWD}/gmsh-4.6.0-Linux64-sdk/lib:${PATH}
  - export INCLUDE=${PWD}/gmsh-4.6.0-Linux64-sdk/include:${INCLUDE}
  - export LIB=${PWD}/gmsh-4.6.0-Linux64-sdk/lib:${LIB}
  - export PYTHONPATH=${PWD}/gmsh-4.6.0-Linux64-sdk/lib:${PYTHONPATH}
  - export INCLUDE=${PWD}/eigen-3.3.7/:${INCLUDE}
  - mkdir build
  - cd build
  - cmake ../ -DCMAKE_BUILD_TYPE=Release  -G "Unix Makefiles"

script:
  - make