language: cpp

jobs:
  include:
    - os: linux
      dist: focal
      compiler: gcc
    - os: osx
      osx_image: xcode12u
    - os: windows
      env: MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
   
install:
  - if [ $TRAVIS_OS_NAME == linux ]; then 
      sudo apt-get update && sudo apt-get install -y cmake wget tar libgmsh-dev;   
      wget http://gmsh.info/bin/Linux/gmsh-4.6.0-Linux64-sdk.tgz; 
      tar -xf gmsh-4.6.0-Linux64-sdk.tgz; 
      wget https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.gz;
      tar -xf eigen-3.3.7.tar.gz;
    fi 
  - if [ $TRAVIS_OS_NAME == osx ]; then 
      brew update && brew install cmake wget gnu-tar llvm libomp;
      wget http://gmsh.info/bin/MacOSX/gmsh-4.6.0-MacOSX-sdk.tgz; 
      gtar -xf gmsh-4.6.0-MacOSX-sdk.tgz; 
      wget https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.gz;
      gtar -xf eigen-3.3.7.tar.gz;
    fi
  - if [ $TRAVIS_OS_NAME == windows ]; then 
      choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64";
      wget http://gmsh.info/bin/Windows/gmsh-4.6.0-Windows64-sdk.zip; 
      7z x gmsh-4.6.0-Windows64-sdk.zip; 
      wget https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.gz;
      7z x eigen-3.3.7.tar.gz;
    fi 

before_script:  
  - if [ $TRAVIS_OS_NAME == linux ]; then
      export PATH=${PWD}/gmsh-4.6.0-Linux64-sdk/bin:${PWD}/gmsh-4.6.0-Linux64-sdk/lib:${PATH};
      export INCLUDE=${PWD}/gmsh-4.6.0-Linux64-sdk/include:${INCLUDE};
      export LIB=${PWD}/gmsh-4.6.0-Linux64-sdk/lib:${LIB};
      export PYTHONPATH=${PWD}/gmsh-4.6.0-Linux64-sdk/lib:${PYTHONPATH};
      export INCLUDE=${PWD}/eigen-3.3.7/:${INCLUDE};
    fi
  - if [ $TRAVIS_OS_NAME == osx ]; then
      export PATH=${PWD}/gmsh-4.6.0-MacOSX-sdk/bin:${PWD}/gmsh-4.6.0-MacOSX-sdk/lib:${PATH};
      export INCLUDE=${PWD}/gmsh-4.6.0-MacOSX-sdk/include:${INCLUDE};
      export LIB=${PWD}/gmsh-4.6.0-MacOSX-sdk/lib:${LIB};
      export PYTHONPATH=${PWD}/gmsh-4.6.0-MacOSX-sdk/lib:${PYTHONPATH};
      export INCLUDE=${PWD}/eigen-3.3.7/:${INCLUDE};
    fi 
  - if [ $TRAVIS_OS_NAME == windows ]; then
      export PATH=${PWD}/gmsh-4.6.0-Windows64-sdk/bin:${PWD}/gmsh-4.6.0-Windows64-sdk/lib:${PATH};
      export INCLUDE=${PWD}/gmsh-4.6.0-Windows64-sdk/include:${INCLUDE};
      export LIB=${PWD}/gmsh-4.6.0-Windows64-sdk/lib:${LIB};
      export PYTHONPATH=${PWD}/gmsh-4.6.0-Windows64-sdk/lib:${PYTHONPATH};
      export INCLUDE=${PWD}/eigen-3.3.7/:${INCLUDE};
    fi 
  - mkdir build
  - cd build
  - if [ $TRAVIS_OS_NAME == linux ]; then
      cmake .. -DCMAKE_BUILD_TYPE=Release  -G "Unix Makefiles";
    fi
  - if [ $TRAVIS_OS_NAME == osx ]; then
      LDFLAGS="-L/usr/local/opt/llvm/lib" CPPFLAGS="-I/usr/local/opt/llvm/include" cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++  -G "Unix Makefiles";
    fi
  - if [ $TRAVIS_OS_NAME == windows ]; then
      export PATH=MSBUILD_PATH:${PATH};
      cmake .. -DCMAKE_BUILD_TYPE=Release  -G "Visual Studio 16 2019" -A x64;
    fi

script:
  - if [ $TRAVIS_OS_NAME == linux ]; then
      make;
    fi
  - if [ $TRAVIS_OS_NAME == osx ]; then
      make;
    fi
  - if [ $TRAVIS_OS_NAME == windows ]; then
      cmake --build;
    fi